sudo: required

services:
  - docker

language: go

go: latest

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y go-md2man

install:
  - go get github.com/openshift/source-to-image
  - pushd ${GOPATH}/src/github.com/openshift/source-to-image
  - export PATH=$PATH:${GOPATH}/src/github.com/openshift/source-to-image/_output/local/bin/linux/amd64/
  - hack/build-go.sh
  - popd

script: SKIP_SQUASH=1 make test TARGET=centos7
